DROP TABLE order_user, orders, users, employees;

CREATE TABLE users (
USER_ID SERIAL PRIMARY KEY,
USERNAME VARCHAR(20) UNIQUE,
USER_PASSWORD VARCHAR(20),
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
BALANCE NUMERIC(20, 2),
SAVED_GAMES INT ARRAY,
PURCHASED_GAMES INT ARRAY
);

CREATE TABLE order_user (
ORDER_USER_ID SERIAL PRIMARY KEY,
USER_ID INT REFERENCES users(USER_ID),
TOTAL_PRICE NUMERIC(20, 2)
);

CREATE TABLE orders (
ORDER_USER_ID INT REFERENCES order_user(ORDER_USER_ID),
GAME_ID INT,
GAME_PRICE NUMERIC(20, 2),
QUANTITY INT
);

CREATE TABLE employees (
EMPLOYEE_ID SERIAL PRIMARY KEY,
EMPLOYEE_USERNAME VARCHAR(20),
EMPLOYEE_PASSWORD VARCHAR(20),
EMAIL VARCHAR(30),
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20)
)
